<?php

/*
 * Implements hook_help()
 */
function trfs_email_subscriptions_help(){
  $ret_val = '';
  switch ($path) {
    case 'admin/help#trfs_email_subscriptions':
      $ret_val = '<h3>'.t('About').'</h3>';
      $ret_val .= '<p>'.t('The email subscription module that allows users to submit there email and alllow amdin user to email those recipents').'</p>';
      break;
  }
  return $ret_val;
}

/*
 * Implements hook_init()
 */
function trfs_email_subscriptions_init(){
  define('TRFS_FORM_PATH', 'includes/');
  module_load_include('inc', 'trfs_email_subscriptions', TRFS_FORM_PATH . 'trfs_email_subscriptions.form');
}

/*
 * Implements hook_menu()
 */
function trfs_email_subscriptions_menu(){
  $items = array();

  $items['admin/config/trfs/trfs-email-subs/settings'] = array(
    'title' => 'TRFS Email Subscriptions',
    'description' => 'Settings page for the TRFS email subscripton module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trfs_email_subscriptions_settings_form'),
    'access arguments' => array('access trfs form settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/trfs_email_subscriptions.admin.inc'
  );

  return $items;
}

/*
 * Implements hook_permission()
 */
function trfs_email_subscriptions_permission(){
  return array(
    'access trfs form settings' => array(
      'title' => t('access TRFS Forms Settings Page'),
    ),
  );
}

/*
 * Implements hook_theme()
 */
function trfs_email_subscriptions_theme(){
  $theme_path = drupal_get_path('theme', 'rarefew');
  $template_directory = $theme_path . '/templates/modules/trfs_email_subscriptions/';

  $items['trfs_email_subscriptions_form'] = array(
    'render element' => 'form',
    'template' => 'trfs-email-subscriptions',
    'path' => $template_directory,
  );

  return $items;
}

/*
 * Implements hook_preprocess_theme()
 */
function trfs_email_subscriptions_preprocess_trfs_email_subscriptions_form(&$vars){
  // show the status messages returned from the form
  // F.Y.I you must disable message printing on all pages first
  $vars['messages'] = theme('status_messages');
}





?>